services:
    laravel:
        build:
            context: backend
            dockerfile: Dockerfile_3
            args:
                WWWGROUP: '1000'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'off'
            XDEBUG_CONFIG: 'client_host=host.docker.internal'
            IGNITION_LOCAL_SITES_PATH: '/PrivateTeacher-Docker'
        networks:
            - sail
        depends_on:
            - pgsql
    pgsql:
        image: 'postgres:17'
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: 'password'
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './backend/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - 'postgres'
                - '-U'
                - 'postgres'
            retries: 30
            timeout: 5s
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        networks:
            - sail
        depends_on:
            - laravel
            - frontend
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
